course_name = "动力学与控制"
course_code = "MECH2021"
repo_type = "normal"

[lecturers]

[[lecturers.items]]
name = "包斌"

[[lecturers.items.reviews]]
content = """
考勤非常频繁，印象中几乎次次有。
平常上课笑呵呵的，其实挺和气。
"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-05" }

[[sections]]
title = "学习资料"

[[sections.items]]
content = "用的是自编课件"
